13210-egzamin-z-asp.net/Models/ErrorViewModel.cs
using System;

namespace _13210_egzamin_z_asp.net.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

13210-egzamin-z-asp.net/Models/StudentsGrades.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace _13210_egzamin_z_asp.net.Models
{
    public class StudentsGrades
    {
        [Required]
        public int StudentsIndex { get; set; }
        [Required]
        [Range(2, 5, ErrorMessage = "Grade musi byc miedzy 2 a 5")]
        public decimal Grade { get; set; }
        [Required]
        public string Subject { get; set; }
    }
}

13210-egzamin-z-asp.net/Controllers/HelloController.cs
using _13210_egzamin_z_asp.net.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _13210_egzamin_z_asp.net.Controllers
{
    public class HelloController : Controller
    {
        static List<StudentsGrades> studentsGrades = new List<StudentsGrades>();
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(StudentsGrades _studentsGrades)
        {
            if (ModelState.IsValid)
            {
                studentsGrades.Add(_studentsGrades);
                return View("List", studentsGrades);
            }
            else
            {
                return View(_studentsGrades);
            }
        }


    }
}

13210-egzamin-z-asp.net/Controllers/HomeController.cs
using _13210_egzamin_z_asp.net.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace _13210_egzamin_z_asp.net.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

13210-egzamin-z-asp.net/Controllers/IndeksController.cs
using _13210_egzamin_z_asp.net.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _13210_egzamin_z_asp.net.Controllers
{
    public class IndeksController : Controller
    {
        static List<StudentsGrades> studentsGrades = new List<StudentsGrades>();
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(StudentsGrades _studentsGrades)
        {
            if (ModelState.IsValid)
            {
                studentsGrades.Add(_studentsGrades);
                return View("List", studentsGrades);
            }
            else
            {
                return View(_studentsGrades);
            }
        }


    }
}

13210-egzamin-z-asp.net/Views/Hello/Index.cshtml
@model _13210_egzamin_z_asp.net.Models.StudentsGrades

<div class="container">
    <form method="post">
        <div class="form-group">
            <label>Index</label>
            <input asp-for="StudentsIndex">
            <span asp-validation-for="StudentsIndex" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label>Grade</label>
            <input asp-for="Grade">
            <span asp-validation-for="Grade" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label>Subject</label>
            <input asp-for="Subject">
            <span asp-validation-for="Subject" class="text-danger"></span>
        </div>
        <button type="submit" class="btn-primary"> ADD</button>
    </form>
</div>

13210-egzamin-z-asp.net/Views/Hello/List.cshtml
@model ICollection<_13210_egzamin_z_asp.net.Models.StudentsGrades>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<table class="table">
    <thead>
        <tr>
            <th scope="col"> Index</th>
            <th scope="col"> Grade</th>
            <th scope="col"> Subject</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <th>@item.StudentsIndex</th>
                <th>@item.Grade</th>
                <th>@item.Subject</th>

            </tr>
        }

    </tbody>
</table>

13210-egzamin-z-asp.net/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

13210-egzamin-z-asp.net/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _13210_egzamin_z_asp.net</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">_13210_egzamin_z_asp.net</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hello" asp-action="Index">Hello</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - _13210_egzamin_z_asp.net - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>